- hosts: masters
  become: yes
  tasks:
    - name: containerd
      shell: sudo kubeadm config images pull --cri-socket unix:///run/containerd/containerd.sock
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///run/containerd/containerd.sock
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: root
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root

    - name: install Pod network
      become: yes
      become_user: root
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/calico.yaml 
      args:
        chdir: $HOME

    - name: Get the token for joining the worker nodes
      become: yes
      become_user: root
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
       msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

